### ISSUE TITLE
Farm multiprocessing

### ISSUE THREAD

**Issue by SaraJakubiak** [resistance-modelling/slim#11]
Investigate running Farm updates concurrently.

**Comment by SaraJakubiak** [comment]
Currently implemented logging is likely not suitable for multiprocessing - investigate further.

**Comment by erolm-a** [comment]
According to [TDS](https://towardsdatascience.com/8-advanced-python-logging-features-that-you-shouldnt-miss-a68a5ef1b62d) logging is thread safe already.

The main issue is lockstep updates. I am concerned there may be little gain if every day egg batches need to be propagated across farms.

**Comment by erolm-a** [comment]
As the model is increasing in complexity I believe an attempt to test multithreading/multiprocessing should be done.

For now, I'd prefer to keep multithreading to the level of farms.
Python's way to do multithreading and multiprocessing leaves a lot to be desired, at least in my personal experience. To overcome this we should consider the adoption of [ray](https://www.ray.io/). It covers a number of aspects including logging.

For starters, I would likely parallelise the Farm classes as their individual update methods are relatively expensive. This assumption may obviously be wrong, which is why some benchmarking should be performed.

**Comment by erolm-a** [comment]
The latest commit introduces ray and farm updates. Event queues are still serialised.
Preliminary results show a 5-6x performance increase. This is surprising given that there is still plenty of logging (which would require a mutex lock as actors do not define their own) and shared resources - although none of them is global (see [this](https://numpy.org/doc/stable/reference/random/parallel.html)).

We believe optimising these bottlenecks would allow us to reach an even higher boost. This would also include but is not limited to using numba for critical code paths, but it will likely be postponed.

**Comment by erolm-a** [comment]
ray is not the way to go, unfortunately. We will likely retry with numba or other hybrid approaches that can disable the GIL.
