### ISSUE TITLE
Translate between genotype varieties and population resistance parameters

### ISSUE THREAD

**Issue by magicicada** [resistance-modelling/slim#36]
Once the mating code is added, write translators for the population genotype distributions to population distributions of resistance suitable for use in the treatment mortatlity of lice calculation.

**Comment by anthonyohare** [comment]
It looks like we need to decide what treatment strategy we are modelling as the resistent mechanism depends on the treatment. Here is Armin's email:

It may be useful to try model different scenarios aligning to what is known about different therapeutics and  the resistance affecting them.

while multiresistant lice are common, i.e. lice  that are simultaneously resistant against different chemicals,  the resistance against each chemical class seems to be caused by specific mechanisms. 
there are currently five chemical classes in use:
organophosphates - one compound used: azamethiphos (AZM)  (other OPs were in use before 1998)
oxidants -  one compound used: hydrogen peroxide (H2O2)
pyrethroids - two compounds used (Norway) : deltamethrin (DTM) and cypermethrin (latter not currently available in UK)
avermectins: one compound used: emamectin benzoate (EB)
benzoylureas: two compounds used (Norway): Diflubenzuron Teflubenzuron (not avaiolable in UK)

Resistance is thus common against all of the drugs available in the UK: AZM, H2O2, DTM and EB. 

Mechanisms/Genetics:

Resistance against AZM appears to be monogenic, with incomplete dominance.
Homozygote resistant individuals show 100% of likelihood to survive treatments, heterozygotes ~50%, wild type close to 0%
lKaur, K., Helgesen, K. O., Bakke, M. J., & Horsberg, T. E. (2015). Mechanism behind resistance against the organophosphate azamethiphos in salmon lice (Lepeophtheirus salmonis). PloS One, 10(4), e0124220. https://doi.org/10.1371/journal.pone.0124220

Resistance against DTM is mainly affected by mitochondrial haplotype, with the effect of unidentified other genes being minor.
I think available evidence justifies modelling this taking into acccount only the mitochondrial genes.
Thus a monogenic mechanism with non-Mendelian in heritance.
Lice carrying the resistant mitochondrial haplotype are 100% resistant.
Female but not male resistant lice pass the resistance on to their offspring.
Carmona-Antoñanzas, G., Bekaert, M., Humble, J. L., Boyd, S., Roy, W., Bassett, D. I., Houston, R. D., Gharbi, K., Bron, J. E., & Sturm, A. (2017). Maternal inheritance of deltamethrin resistance in the salmon louse Lepeophtheirus salmonis (Krøyer) is associated with unique mtDNA haplotypes. PLoS ONE, 12(7), e0180625. https://doi.org/10.1371/journal.pone.0180625

Resistance against EB has been mapped to a region on one chromosome, suggesting  monogenic resistance or several closely spaced genes.
The exact effect on phenotype is more difficult to work out, as the compound is a feed treatment, but lice are usually characterised using bioassays with waterborne exposure.
From available evidence it is reasonable to assume for the sake of modelling also monogenic mechanism and incomplete dominance, but perhaps a bit less than 100% resistance in the homozygous resistant parasites. Also the drug seems still to ve effective in reducing settlement of lice larvae, which is why it is still used at the beginning oif the marine production cycle (fish treated at time aroiund sea transfer)
The treatment coiurse is 7 days and protects the fish for ~six weeks against infection (that was before resistance --- not sure whether that has changed and if yes how)

Besnier, F., Kent, M., Skern-Mauritzen, R., Lien, S., Malde, K., Edvardsen, R. B., Taylor, S., Ljungfeldt, L. E., Nilsen, F., & Glover, K. A. (2014). Human-induced evolution caught in action: SNP-array reveals rapid amphi-atlantic spread of pesticide resistance in the salmon ecotoparasite Lepeophtheirus salmonis. BMC Genomics, 15(1), 937. https://doi.org/10.1186/1471-2164-15-937


Resistance against  H2O2 seems to be affected by different genes, and full resistance seems to require regular  drug exposure, as resistance levels decline when lice are kept in lab without treatments.
Available data do not really allow clear indications - fully resistant lice seem to be 70% resistant against standard dose of treatment, when they are kept in the absence of selection this decreases to about 50%. Unclear whether incompletely of fully dominant.
Agusti-Ridaura, C., Bakke, M. J., Helgesen, K. O., Sundaram, A. Y. M., Bakke, S. J., Kaur, K., & Horsberg, T. E. (2020). Candidate genes for monitoring hydrogen peroxide resistance in the salmon louse, Lepeophtheirus salmonis. Parasites and Vectors, 13(1), 1–16. https://doi.org/10.1186/s13071-020-04211-1

Thus, it may be the best to focus on AZM and DTM, as the situation is clearest here
For these drugs there are also some published data about resistance allele frequencies and resistance levels  in field populations.
These two drugs offer a nice contrast. If you get bored with that you could next use what is known about the other drugs to play around with parameters and see what happens if you change assumptions.

I tried to keep this sweet and short, hope this is useful --- happy to discuss and go into more detail if you want. But will be off on AL from Friday on until end of the month.

Field data on AZM and DTM resistance:
Jensen, E. M., Horsberg, T. E., Sevatdal, S., & Helgesen, K. O. (2020). Trends in de-lousing of Norwegian farmed salmon from 2000–2019—Consumption of medicines, salmon louse resistance and non-medicinal control methods. PLoS ONE, 15(10 October). https://doi.org/10.1371/journal.pone.0240894
Fjørtoft, H. B., Nilsen, F., Besnier, F., Stene, A., Tveten, A. K., Bjørn, P. A., Aspehaug, V. T., & Glover, K. A. (2021). Losing the “arms race”: Multiresistant salmon lice are dispersed throughout the North Atlantic Ocean. Royal Society Open Science, 8(5). https://doi.org/10.1098/rsos.210265
Børretzen Fjørtoft, H., Nilsen, F., Besnier, F., Stene, A., Bjørn, P., Tveten, A., Aspehaug, V., Finstad, B., & Glover, K. (2019). Salmon lice sampled from wild Atlantic salmon and sea trout throughout Norway display high frequencies of the genotype associated with pyrethroid resistance. Aquaculture Environment Interactions, 11, 459–468. https://doi.org/10.3354/aei00322
Fjørtoft, H. B., Besnier, F., Stene, A., Nilsen, F., Bjørn, P. A., Tveten, A. K., Finstad, B., Aspehaug, V., & Glover, K. A. (2017). The Phe362Tyr mutation conveying resistance to organophosphates occurs in high frequencies in salmon lice collected from wild salmon and trout. Scientific Reports, 7(1), 1–10. https://doi.org/10.1038/s41598-017-14681-6
Fjørtoft, H. B., Nilsen, F., Besnier, F., Espedal, P. G., Stene, A., Bjørn, A., Aspehaug, V. T., Glover, K. A., & Tveten, A. (2020). Aquaculture-driven evolution: distribution of pyrethroid resistance in the salmon louse throughout the North Atlantic in the years 2000-2017. ICES Journal of Marine Science. https://doi.org/10.1093/icesjms/fsaa062
Kaur, K., Besnier, F., Glover, K. A., Nilsen, F., Aspehaug, V. T., Fjørtoft, H. B., & Horsberg, T. E. (2017). The mechanism (Phe362Tyr mutation) behind resistance in Lepeophtheirus salmonis pre-dates organophosphate use in salmon farming. Scientific Reports, 7(1), 12349. https://doi.org/10.1038/s41598-017-12384-6
