### ISSUE TITLE
Life stage and genotype distribution of lice incoming from reservoir 

### ISSUE THREAD

**Issue by SaraJakubiak** [resistance-modelling/slim#45]
Only L1 and L2 can move from reservoir to farms. At the moment the external pressure is a number of both L1 and L2 and the number of lice in either stage is then randomly decided.

After a brief discussion it was noted that the ratio between L1 and L2 should be taken into account - this requires further data.

Similarly, to update the population with lice from reservoir information about the genotype on incoming lice is required.

**Comment by magicicada** [comment]
Plan: ask Armin in August

**Comment by erolm-a** [comment]
Indeed, @anthonyohare and I asked him but I can't remember exactly what he said. I think however the bottom line was that one should expect a dynamism in genotype distribution as a lake becomes saturated with resistant lice but as for the "how", we miss a model. As for the the life stages he does not know and it likely is not that big of an issue in our model right now. Hopefully we can retrieve better info from some notes, hoping he still kept them.

Because of the recent results of the model we believe it should be a good idea to move towards the implementation of production cycles, thus a dynamic reservoir is absolutely needed as discussed in #162 .
